- Doppler.UsersApi.Test/AuthorizationTest.cs
- Doppler.UsersApi.Test/Controllers/HelloController.cs
- Doppler.UsersApi.Test/Utils/HttpResponseMessageExtensions.cs
I created a fake controller (HelloController) in test project to support the authorization test.
Also I copied and pasted the authorization test from hello microservice project
> test: move test controller to test project

- Doppler.UsersApi.Test/Doppler.UsersApi.Test.csproj
- Doppler.UsersApi.Test/GetFeaturesTest.cs
- Doppler.UsersApi.Test/IntegrationTest.cs
- Doppler.UsersApi.Test/Utils/ServiceCollectionExtensions.cs
- Doppler.UsersApi/Controllers/FeatureController.cs
- Doppler.UsersApi/Doppler.UsersApi.csproj
- Doppler.UsersApi/Infrastructure/DatabaseConnectionFactory.cs
- Doppler.UsersApi/Infrastructure/DopplerDatabaseSettings.cs
- Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
- Doppler.UsersApi/Infrastructure/IDatabaseConnectionFactory.cs
- Doppler.UsersApi/Infrastructure/IDopplerDatabaseSettings.cs
- Doppler.UsersApi/Infrastructure/IFeaturesRepository.cs
- Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.UsersApi/Logging/SerilogSetup.cs
- Doppler.UsersApi/Model/Features.cs
- Doppler.UsersApi/Startup.cs
- Doppler.UsersApi/appsettings.Development.json
- Doppler.UsersApi/appsettings.json
Complete functionality to get features from database (controller, repository, database query).
Unit test for repositories (using a moq-dapper library) https://github.com/UnoSD/Moq.Dapper.
Unit test for controller.
> feat: give functionality to features endpoint

- Doppler.UsersApi.Test/GetContactInformationTest.cs
- Doppler.UsersApi/Controllers/AccountController.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Infrastructure/IAccountRepository.cs
- Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.UsersApi/Model/ContactInformation.cs
Add new account controller with get contact information endpoint.
> Dat 466 add account controller with contact information endpoint

- Doppler.UsersApi/Infrastructure/AccountRepository.cs
remove city join in database query
> fix: remove city join in database query

- Doppler.UsersApi/Startup.cs
add CORS support to the service
> feature: add cors support

- Doppler.UsersApi/Infrastructure/AccountRepository.cs
Update the endpoint that get user contact information, in order to return the Industry code intead of its ID.
> [DAT-504] - Return Industry code

- Doppler.UsersApi.Test/UpdateContactInformationTest.cs
- Doppler.UsersApi/Controllers/AccountController.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Infrastructure/IAccountRepository.cs
- Doppler.UsersApi/Model/ContactInformation.cs
Add new endpoint to update user contact information. 
*So far, there is no Code field in the table State, so that is a TODO. The update is not working for State and Country properties.
> [DAT-489] - Add update contact information endpoint

- Doppler.UsersApi/Infrastructure/AccountRepository.cs
return the state code in province attribute
> feat: return state code in province attribute

- Doppler.UsersApi.Test/GetFeaturesTest.cs
- Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
- Doppler.UsersApi/Model/Features.cs
> feat: add new features

- Doppler.UsersApi/Infrastructure/AccountRepository.cs
return state code on update, if the state is not register in doppler db, return the default state for the selected country
> feat: return state code on update

- Dockerfile
- Doppler.UsersApi.Test/EncryptionTest/EncryptionEnvironmentTests.cs
- Doppler.UsersApi.Test/EncryptionTest/EncryptionServiceTests.cs
- Doppler.UsersApi.Test/EncryptionTest/EncryptionServiceWithRealConfigurationTests.cs
- Doppler.UsersApi.Test/EncryptionTest/EncryptionTestHelpers.cs
- Doppler.UsersApi.Test/GetContactInformationTest.cs
- Doppler.UsersApi/Encryption/EncryptionService.cs
- Doppler.UsersApi/Encryption/EncryptionSettings.cs
- Doppler.UsersApi/Encryption/IEncryptionService.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Model/ContactInformation.cs
- Doppler.UsersApi/Startup.cs
- Doppler.UsersApi/appsettings.Development.json
- Jenkinsfile
- build-n-publish.sh
We need to Decrypt and Encrypt security questions to answers in the contact information section
In additionally add in getting billing contact information endpoint, the two properties
> feat: [DAT-526] Add decrypt/encrypt service

- Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
- Doppler.UsersApi.Test/GetContactInformationTest.cs
- Doppler.UsersApi.Test/UpdateContactInformationTest.cs
- Doppler.UsersApi/Controllers/AccountController.cs
- Doppler.UsersApi/Doppler.UsersApi.csproj
- Doppler.UsersApi/Encryption/EncryptionService.cs
- Doppler.UsersApi/Encryption/IEncryptionService.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Startup.cs
- Doppler.UsersApi/Validators/ContactInformationValidator.cs
We need to limit the amount of characters for the properties
> feat: [DAT-537] add validations for contact information

- Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Validators/ContactInformationValidator.cs
We need to wait for Task https://makingsense.atlassian.net/browse/DAT-525 to add validator and encryption
> chore: [No ticket ] Remove answer question validate and encryption

- Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
- Doppler.UsersApi/Validators/ContactInformationValidator.cs
We need to remove unnecessary validation of `answerSecurityQuestion ` property
> fix: [No-Ticket] Remove unnecessary validation

- Doppler.UsersApi/appsettings.Development.json
These configs aren't necessary
> fix: [No-ticket] Remove unnecessary config

- Doppler.UsersApi.Test/GetIntegrationsTest.cs
- Doppler.UsersApi/Controllers/IntegrationController.cs
- Doppler.UsersApi/Infrastructure/IIntegrationsRepository.cs
- Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.UsersApi/Infrastructure/IntegrationsRepository.cs
- Doppler.UsersApi/Model/Integrations.cs
This new endpoint will return the status of the integrations (connected, disconected and warning) for a given user.
> [DOI-331] add integrations endpoint

- Doppler.UsersApi/Infrastructure/IntegrationsRepository.cs
- Doppler.UsersApi/Model/Integrations.cs
Add vtex, google analitycs and Big query's connection status into endpoint response.
Also, modify the amount of errors to return "alert" status.
> [DOI-376] feat: Add new integrations status

- Doppler.UsersApi/Infrastructure/IntegrationsRepository.cs
It was returning wrong data in some cases. This should fix it.
> Fix integration status query

- Doppler.UsersApi.Test/Utils/ServiceCollectionExtensions.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Infrastructure/DatabaseConnectionFactory.cs
- Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
- Doppler.UsersApi/Infrastructure/IDatabaseConnectionFactory.cs
- Doppler.UsersApi/Infrastructure/IntegrationsRepository.cs
Please look at this PR where this problem was found: https://github.com/FromDoppler/doppler-html-editor-api/pull/42
~~**Pending: I can not pass tests local**~~
> Fix to do not open db connection on factory

- .github/dependabot.yml
dependabot config file used in repositories like https://github.com/FromDoppler/doppler-contact-policies-api
> Add dependabot assistant

- Doppler.UsersApi.Test/GetFeaturesTest.cs
- Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
- Doppler.UsersApi/Model/Features.cs
the "ContactPolicies" feature always will be true for all users
related to DOP-1080
> refactor: consider "ContactPolicies" feature true

- Doppler.UsersApi/Doppler.UsersApi.csproj
- Doppler.UsersApi/Services/EmailSender/EmailData.cs
- Doppler.UsersApi/Services/EmailSender/EmailSenderServiceExtensionCollectionExtensions.cs
- Doppler.UsersApi/Services/EmailSender/IEmailSender.cs
- Doppler.UsersApi/Services/EmailSender/RelayEmailSender.cs
- Doppler.UsersApi/Services/EmailSender/RelayEmailSenderSettings.cs
- Doppler.UsersApi/Startup.cs
- Doppler.UsersApi/appsettings.json
This PR is for implementing the service for sending emails using `Relay`
> [DOI-1495] Allow send emails with Relay

- Doppler.UsersApi.Test/GetRelatedUsersByTypeTest.cs
- Doppler.UsersApi/Controllers/AccountController.cs
- Doppler.UsersApi/Infrastructure/AccountRepository.cs
- Doppler.UsersApi/Infrastructure/IAccountRepository.cs
- Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
- Doppler.UsersApi/Model/ColaborationInvitationModel.cs
- Doppler.UsersApi/Model/ColaborationInvite.cs
- Doppler.UsersApi/Model/Enums/InviteStatusEnum.cs
- Doppler.UsersApi/Model/InvitationInformation.cs
- Doppler.UsersApi/Services/AccountService.cs
- Doppler.UsersApi/Services/AccountServiceSettings.cs
- Doppler.UsersApi/Services/IAccountService.cs
- Doppler.UsersApi/Startup.cs
- Doppler.UsersApi/appsettings.json
This endpoint should add a new collaboration invite or update an existing one.
Any feedback is more than welcome 😄
> [DOI-1392] Add Collaborator invitation endpoint
